### ISSUE TITLE
modelTest() function not available

### ISSUE THREAD

**Issue by amyclairet** [JWiley/multilevelTools#1]
Hi Joshua,

I just wanted to let you know that the modelTest() function you describe in your function documentation and at https://cran.r-project.org/web/packages/multilevelTools/vignettes/lmer-vignette.html is not currently available in the package.

Thanks.

**Comment by JWiley** [comment]
@amyclairet `multilevelTools` adds additional methods to the `modelTest()` function to support multilevel models. The generic `modelTest()` function (which is needed to call the methods) is in the `JWileymisc` package.

If you load the packages used at the top of that vignette it should work.
