### ISSUE TITLE
Functions not available

### ISSUE THREAD

**Issue by drewwint** [JWiley/multilevelTools#2]
Hi - many of the great functions for multilevel tools are not available when I install from cran or GitHub. there or only 5 functions available to use and which do not include "modelTest", "APAstyler", "modelCompare" and many others.

Additionally when I install directly from GitHub it throughs errors when accessing the helper files of the available functions.

**Comment by JWiley** [comment]
@drewwint sounds like you need `JWileymisc` installed as well. The current, somewhat awkward, setup is:

- for lack of a better place, `JWileymisc` defines the generics for `modelTest()`, etc. and implements methods for linear regression. If those got full featured enough, might move into a separate package for regression tools or something but right now feels too small to stand alone so just left in `JWileymisc`.
- `multilevelTools` implements methods only for multilevel models via `lme4` (and considering expanding to some other multilevel packages, like `nlme` and `brms`).

Installing from CRAN should pull the dependencies, try:

```
install.packages("multilevelTools", dependencies = TRUE)

library(JWileymisc)
library(multilevelTools)
```

and it should work. See examples here: http://joshuawiley.com/multilevelTools/articles/lmer-vignette.html
