### ISSUE TITLE
Unable to install multilevelTools package

### ISSUE THREAD

**Issue by LizMansi** [JWiley/multilevelTools#3]
Hi,

I found your vignette and seemed it would be very helpful. However, I can't install your 'multilevelTools' package (I tried devtools::install_github("JWiley/multilevelTools") as well). Any suggestions?

Warning messages:
1: package ‘estimability’ is not available for this version of R
‘estimability’ version 1.5 is in the repositories but depends on R(>= 4.3.0)

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) : installation of package ‘nloptr’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘emmeans’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘JWileymisc’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘/tmp/RtmpxvJ0mK/file15c6dd3dbd908b/multilevelTools_0.1.3.tar.gz’ had non-zero exit status

Thanks,
Liz

**Comment by JWiley** [comment]
Hi Liz,

From the note it looks like you need R version 4.3.0 or greater. Can you
try downloading and installing latest version and trying again?

I also note you can get multilevelTools from CRAN which may be easier.

Best wishes, Josh

**Comment by LizMansi** [comment]
Ah, right, thank you. Annoying for me because I'm working on a Remote Desktop and don't have the access to update R :/ Thanks for the quick reply!

**Comment by JWiley** [comment]
Closing this for now but if updated R does not resolve please feel free to reopen or open a new issue.
